version: "3.9"

services:

  automl_api:

    build:
      context: ../../

      dockerfile: src/deployment/Dockerfile

    container_name: industrial_automl_api

    ports:
      - "8000:8000"

    volumes:
      - ../../:/app

    restart: unless-stopped